version: 2.1

executors:
  gem-executor:
    working_directory: ~/tmp/gem
    docker:
      - image: circleci/ruby:2.7.5
    environment:
      TZ: "Europe/Madrid"

jobs:
  build-test-gem:
    executor: gem-executor
    steps:
      - checkout

      - run:
          name: Update bundler
          command: gem install bundler -v 2.2.20

      - restore_cache:
          keys:
            - afterbanks-api-ruby-bundle-v2-{{ checksum "Gemfile.lock" }}
            - afterbanks-api-ruby-bundle-v2-

      - run: bundle install

      - save_cache:
          key: afterbanks-api-ruby-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run rspec
          command: bundle exec rspec spec/

workflows:
  build-test-gem:
    jobs:
      - build-test-gem
